-- Script para modificar claves foráneas con ON DELETE CASCADE

ALTER TABLE JUGADOR DROP CONSTRAINT FK_JUGADOR_EQUIPO;
ALTER TABLE JUGADOR ADD CONSTRAINT FK_JUGADOR_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE;

ALTER TABLE JUGADOR DROP CONSTRAINT FK_JUGADOR_UBICACION;
ALTER TABLE JUGADOR ADD CONSTRAINT FK_JUGADOR_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION) ON DELETE CASCADE;

ALTER TABLE PRESIDENTE DROP CONSTRAINT FK_PRESIDENTE_UBICACION;
ALTER TABLE PRESIDENTE ADD CONSTRAINT FK_PRESIDENTE_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION) ON DELETE CASCADE;

ALTER TABLE EQUIPO DROP CONSTRAINT FK_EQUIPO_PRESIDENTE;
ALTER TABLE EQUIPO ADD CONSTRAINT FK_EQUIPO_PRESIDENTE FOREIGN KEY (ID_PRESIDENTE) REFERENCES PRESIDENTE(ID_PRESIDENTE) ON DELETE CASCADE;

ALTER TABLE EQUIPO DROP CONSTRAINT FK_EQUIPO_UBICACION;
ALTER TABLE EQUIPO ADD CONSTRAINT FK_EQUIPO_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION) ON DELETE CASCADE;

ALTER TABLE PARTIDO DROP CONSTRAINT FK_PARTIDO_UBICACION;
ALTER TABLE PARTIDO ADD CONSTRAINT FK_PARTIDO_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION) ON DELETE CASCADE;

ALTER TABLE PARTIDO_EQUIPO DROP CONSTRAINT FK_PE_PARTIDO;
ALTER TABLE PARTIDO_EQUIPO ADD CONSTRAINT FK_PE_PARTIDO FOREIGN KEY (ID_PARTIDO) REFERENCES PARTIDO(ID_PARTIDO) ON DELETE CASCADE;

ALTER TABLE PARTIDO_EQUIPO DROP CONSTRAINT FK_PE_EQUIPO;
ALTER TABLE PARTIDO_EQUIPO ADD CONSTRAINT FK_PE_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE;

ALTER TABLE GOL DROP CONSTRAINT FK_GOL_JUGADOR;
ALTER TABLE GOL ADD CONSTRAINT FK_GOL_JUGADOR FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR(ID_JUGADOR) ON DELETE CASCADE;

ALTER TABLE GOL DROP CONSTRAINT FK_GOL_PARTIDO;
ALTER TABLE GOL ADD CONSTRAINT FK_GOL_PARTIDO FOREIGN KEY (ID_PARTIDO) REFERENCES PARTIDO(ID_PARTIDO) ON DELETE CASCADE;

