CREATE TABLE BITACORA_CAMBIOS (
    ID_BITACORA NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOMBRE_TABLA VARCHAR2(50) NOT NULL,
    OPERACION VARCHAR2(10) NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_BD VARCHAR2(30), -- Usuario que hizo el cambio
    VALOR_ANTERIOR CLOB, -- JSON con los datos antes del cambio (solo para UPDATE y DELETE)
    VALOR_NUEVO CLOB -- JSON con los datos después del cambio (solo para INSERT y UPDATE)
);
commit;

-- Trigger para la tabla UBICACION
CREATE OR REPLACE TRIGGER TRG_UBICACION_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON UBICACION
FOR EACH ROW
DECLARE
    v_old CLOB := '{';
    v_new CLOB := '{';
BEGIN
    IF INSERTING THEN
        v_new := v_new || '"ID_UBICACION":' || '"' || TO_CHAR(:NEW.ID_UBICACION) || '"' || ',';
        v_new := v_new || '"DEPARTAMENTO":' || '"' || TO_CHAR(:NEW.DEPARTAMENTO) || '"' || ',';
        v_new := v_new || '"MUNICIPIO":' || '"' || TO_CHAR(:NEW.MUNICIPIO) || '"' || ',';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_NUEVO)
        VALUES ('UBICACION', 'INSERT', USER, v_new);

    ELSIF UPDATING THEN
        v_old := v_old || '"ID_UBICACION":' || '"' || TO_CHAR(:OLD.ID_UBICACION) || '"' || ',';
        v_new := v_new || '"ID_UBICACION":' || '"' || TO_CHAR(:NEW.ID_UBICACION) || '"' || ',';
        v_old := v_old || '"DEPARTAMENTO":' || '"' || TO_CHAR(:OLD.DEPARTAMENTO) || '"' || ',';
        v_new := v_new || '"DEPARTAMENTO":' || '"' || TO_CHAR(:NEW.DEPARTAMENTO) || '"' || ',';
        v_old := v_old || '"MUNICIPIO":' || '"' || TO_CHAR(:OLD.MUNICIPIO) || '"' || ',';
        v_new := v_new || '"MUNICIPIO":' || '"' || TO_CHAR(:NEW.MUNICIPIO) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES ('UBICACION', 'UPDATE', USER, v_old, v_new);

    ELSIF DELETING THEN
        v_old := v_old || '"ID_UBICACION":' || '"' || TO_CHAR(:OLD.ID_UBICACION) || '"' || ',';
        v_old := v_old || '"DEPARTAMENTO":' || '"' || TO_CHAR(:OLD.DEPARTAMENTO) || '"' || ',';
        v_old := v_old || '"MUNICIPIO":' || '"' || TO_CHAR(:OLD.MUNICIPIO) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR)
        VALUES ('UBICACION', 'DELETE', USER, v_old);
    END IF;
END;
/

-- Trigger para la tabla PRESIDENTE
CREATE OR REPLACE TRIGGER TRG_PRESIDENTE_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON PRESIDENTE
FOR EACH ROW
DECLARE
    v_old CLOB := '{';
    v_new CLOB := '{';
BEGIN
    IF INSERTING THEN
        v_new := v_new || '"ID_PRESIDENTE":' || '"' || TO_CHAR(:NEW.ID_PRESIDENTE) || '"' || ',';
        v_new := v_new || '"DPI":' || '"' || TO_CHAR(:NEW.DPI) || '"' || ',';
        v_new := v_new || '"NOMBRE1":' || '"' || TO_CHAR(:NEW.NOMBRE1) || '"' || ',';
        v_new := v_new || '"NOMBRE2":' || '"' || TO_CHAR(:NEW.NOMBRE2) || '"' || ',';
        v_new := v_new || '"NOMBRE3":' || '"' || TO_CHAR(:NEW.NOMBRE3) || '"' || ',';
        v_new := v_new || '"APELLIDO1":' || '"' || TO_CHAR(:NEW.APELLIDO1) || '"' || ',';
        v_new := v_new || '"APELLIDO2":' || '"' || TO_CHAR(:NEW.APELLIDO2) || '"' || ',';
        v_new := v_new || '"FECHA_NACIMIENTO":' || '"' || TO_CHAR(:NEW.FECHA_NACIMIENTO) || '"' || ',';
        v_new := v_new || '"CORREO":' || '"' || TO_CHAR(:NEW.CORREO) || '"' || ',';
        v_new := v_new || '"ID_UBICACION":' || '"' || TO_CHAR(:NEW.ID_UBICACION) || '"' || ',';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_NUEVO)
        VALUES ('PRESIDENTE', 'INSERT', USER, v_new);

    ELSIF UPDATING THEN
        v_old := v_old || '"ID_PRESIDENTE":' || '"' || TO_CHAR(:OLD.ID_PRESIDENTE) || '"' || ',';
        v_new := v_new || '"ID_PRESIDENTE":' || '"' || TO_CHAR(:NEW.ID_PRESIDENTE) || '"' || ',';
        v_old := v_old || '"DPI":' || '"' || TO_CHAR(:OLD.DPI) || '"' || ',';
        v_new := v_new || '"DPI":' || '"' || TO_CHAR(:NEW.DPI) || '"' || ',';
        v_old := v_old || '"NOMBRE1":' || '"' || TO_CHAR(:OLD.NOMBRE1) || '"' || ',';
        v_new := v_new || '"NOMBRE1":' || '"' || TO_CHAR(:NEW.NOMBRE1) || '"' || ',';
        v_old := v_old || '"NOMBRE2":' || '"' || TO_CHAR(:OLD.NOMBRE2) || '"' || ',';
        v_new := v_new || '"NOMBRE2":' || '"' || TO_CHAR(:NEW.NOMBRE2) || '"' || ',';
        v_old := v_old || '"NOMBRE3":' || '"' || TO_CHAR(:OLD.NOMBRE3) || '"' || ',';
        v_new := v_new || '"NOMBRE3":' || '"' || TO_CHAR(:NEW.NOMBRE3) || '"' || ',';
        v_old := v_old || '"APELLIDO1":' || '"' || TO_CHAR(:OLD.APELLIDO1) || '"' || ',';
        v_new := v_new || '"APELLIDO1":' || '"' || TO_CHAR(:NEW.APELLIDO1) || '"' || ',';
        v_old := v_old || '"APELLIDO2":' || '"' || TO_CHAR(:OLD.APELLIDO2) || '"' || ',';
        v_new := v_new || '"APELLIDO2":' || '"' || TO_CHAR(:NEW.APELLIDO2) || '"' || ',';
        v_old := v_old || '"FECHA_NACIMIENTO":' || '"' || TO_CHAR(:OLD.FECHA_NACIMIENTO) || '"' || ',';
        v_new := v_new || '"FECHA_NACIMIENTO":' || '"' || TO_CHAR(:NEW.FECHA_NACIMIENTO) || '"' || ',';
        v_old := v_old || '"CORREO":' || '"' || TO_CHAR(:OLD.CORREO) || '"' || ',';
        v_new := v_new || '"CORREO":' || '"' || TO_CHAR(:NEW.CORREO) || '"' || ',';
        v_old := v_old || '"ID_UBICACION":' || '"' || TO_CHAR(:OLD.ID_UBICACION) || '"' || ',';
        v_new := v_new || '"ID_UBICACION":' || '"' || TO_CHAR(:NEW.ID_UBICACION) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES ('PRESIDENTE', 'UPDATE', USER, v_old, v_new);

    ELSIF DELETING THEN
        v_old := v_old || '"ID_PRESIDENTE":' || '"' || TO_CHAR(:OLD.ID_PRESIDENTE) || '"' || ',';
        v_old := v_old || '"DPI":' || '"' || TO_CHAR(:OLD.DPI) || '"' || ',';
        v_old := v_old || '"NOMBRE1":' || '"' || TO_CHAR(:OLD.NOMBRE1) || '"' || ',';
        v_old := v_old || '"NOMBRE2":' || '"' || TO_CHAR(:OLD.NOMBRE2) || '"' || ',';
        v_old := v_old || '"NOMBRE3":' || '"' || TO_CHAR(:OLD.NOMBRE3) || '"' || ',';
        v_old := v_old || '"APELLIDO1":' || '"' || TO_CHAR(:OLD.APELLIDO1) || '"' || ',';
        v_old := v_old || '"APELLIDO2":' || '"' || TO_CHAR(:OLD.APELLIDO2) || '"' || ',';
        v_old := v_old || '"FECHA_NACIMIENTO":' || '"' || TO_CHAR(:OLD.FECHA_NACIMIENTO) || '"' || ',';
        v_old := v_old || '"CORREO":' || '"' || TO_CHAR(:OLD.CORREO) || '"' || ',';
        v_old := v_old || '"ID_UBICACION":' || '"' || TO_CHAR(:OLD.ID_UBICACION) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR)
        VALUES ('PRESIDENTE', 'DELETE', USER, v_old);
    END IF;
END;
/

-- Trigger para la tabla EQUIPO
CREATE OR REPLACE TRIGGER TRG_EQUIPO_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON EQUIPO
FOR EACH ROW
DECLARE
    v_old CLOB := '{';
    v_new CLOB := '{';
BEGIN
    IF INSERTING THEN
        v_new := v_new || '"ID_EQUIPO":' || '"' || TO_CHAR(:NEW.ID_EQUIPO) || '"' || ',';
        v_new := v_new || '"NOMBRE":' || '"' || TO_CHAR(:NEW.NOMBRE) || '"' || ',';
        v_new := v_new || '"AFORO":' || '"' || TO_CHAR(:NEW.AFORO) || '"' || ',';
        v_new := v_new || '"ANO_FUNDACION":' || '"' || TO_CHAR(:NEW.ANO_FUNDACION) || '"' || ',';
        v_new := v_new || '"ID_PRESIDENTE":' || '"' || TO_CHAR(:NEW.ID_PRESIDENTE) || '"' || ',';
        v_new := v_new || '"ID_UBICACION":' || '"' || TO_CHAR(:NEW.ID_UBICACION) || '"' || ',';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_NUEVO)
        VALUES ('EQUIPO', 'INSERT', USER, v_new);

    ELSIF UPDATING THEN
        v_old := v_old || '"ID_EQUIPO":' || '"' || TO_CHAR(:OLD.ID_EQUIPO) || '"' || ',';
        v_new := v_new || '"ID_EQUIPO":' || '"' || TO_CHAR(:NEW.ID_EQUIPO) || '"' || ',';
        v_old := v_old || '"NOMBRE":' || '"' || TO_CHAR(:OLD.NOMBRE) || '"' || ',';
        v_new := v_new || '"NOMBRE":' || '"' || TO_CHAR(:NEW.NOMBRE) || '"' || ',';
        v_old := v_old || '"AFORO":' || '"' || TO_CHAR(:OLD.AFORO) || '"' || ',';
        v_new := v_new || '"AFORO":' || '"' || TO_CHAR(:NEW.AFORO) || '"' || ',';
        v_old := v_old || '"ANO_FUNDACION":' || '"' || TO_CHAR(:OLD.ANO_FUNDACION) || '"' || ',';
        v_new := v_new || '"ANO_FUNDACION":' || '"' || TO_CHAR(:NEW.ANO_FUNDACION) || '"' || ',';
        v_old := v_old || '"ID_PRESIDENTE":' || '"' || TO_CHAR(:OLD.ID_PRESIDENTE) || '"' || ',';
        v_new := v_new || '"ID_PRESIDENTE":' || '"' || TO_CHAR(:NEW.ID_PRESIDENTE) || '"' || ',';
        v_old := v_old || '"ID_UBICACION":' || '"' || TO_CHAR(:OLD.ID_UBICACION) || '"' || ',';
        v_new := v_new || '"ID_UBICACION":' || '"' || TO_CHAR(:NEW.ID_UBICACION) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES ('EQUIPO', 'UPDATE', USER, v_old, v_new);

    ELSIF DELETING THEN
        v_old := v_old || '"ID_EQUIPO":' || '"' || TO_CHAR(:OLD.ID_EQUIPO) || '"' || ',';
        v_old := v_old || '"NOMBRE":' || '"' || TO_CHAR(:OLD.NOMBRE) || '"' || ',';
        v_old := v_old || '"AFORO":' || '"' || TO_CHAR(:OLD.AFORO) || '"' || ',';
        v_old := v_old || '"ANO_FUNDACION":' || '"' || TO_CHAR(:OLD.ANO_FUNDACION) || '"' || ',';
        v_old := v_old || '"ID_PRESIDENTE":' || '"' || TO_CHAR(:OLD.ID_PRESIDENTE) || '"' || ',';
        v_old := v_old || '"ID_UBICACION":' || '"' || TO_CHAR(:OLD.ID_UBICACION) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR)
        VALUES ('EQUIPO', 'DELETE', USER, v_old);
    END IF;
END;
/

-- Trigger para la tabla JUGADOR
CREATE OR REPLACE TRIGGER TRG_JUGADOR_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON JUGADOR
FOR EACH ROW
DECLARE
    v_old CLOB := '{';
    v_new CLOB := '{';
BEGIN
    IF INSERTING THEN
        v_new := v_new || '"ID_JUGADOR":' || '"' || TO_CHAR(:NEW.ID_JUGADOR) || '"' || ',';
        v_new := v_new || '"NOMBRE1":' || '"' || TO_CHAR(:NEW.NOMBRE1) || '"' || ',';
        v_new := v_new || '"NOMBRE2":' || '"' || TO_CHAR(:NEW.NOMBRE2) || '"' || ',';
        v_new := v_new || '"NOMBRE3":' || '"' || TO_CHAR(:NEW.NOMBRE3) || '"' || ',';
        v_new := v_new || '"APELLIDO1":' || '"' || TO_CHAR(:NEW.APELLIDO1) || '"' || ',';
        v_new := v_new || '"APELLIDO2":' || '"' || TO_CHAR(:NEW.APELLIDO2) || '"' || ',';
        v_new := v_new || '"CORREO_ELECTRONICO":' || '"' || TO_CHAR(:NEW.CORREO_ELECTRONICO) || '"' || ',';
        v_new := v_new || '"POSICION":' || '"' || TO_CHAR(:NEW.POSICION) || '"' || ',';
        v_new := v_new || '"ID_EQUIPO":' || '"' || TO_CHAR(:NEW.ID_EQUIPO) || '"' || ',';
        v_new := v_new || '"ID_UBICACION":' || '"' || TO_CHAR(:NEW.ID_UBICACION) || '"' || ',';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_NUEVO)
        VALUES ('JUGADOR', 'INSERT', USER, v_new);

    ELSIF UPDATING THEN
        v_old := v_old || '"ID_JUGADOR":' || '"' || TO_CHAR(:OLD.ID_JUGADOR) || '"' || ',';
        v_new := v_new || '"ID_JUGADOR":' || '"' || TO_CHAR(:NEW.ID_JUGADOR) || '"' || ',';
        v_old := v_old || '"NOMBRE1":' || '"' || TO_CHAR(:OLD.NOMBRE1) || '"' || ',';
        v_new := v_new || '"NOMBRE1":' || '"' || TO_CHAR(:NEW.NOMBRE1) || '"' || ',';
        v_old := v_old || '"NOMBRE2":' || '"' || TO_CHAR(:OLD.NOMBRE2) || '"' || ',';
        v_new := v_new || '"NOMBRE2":' || '"' || TO_CHAR(:NEW.NOMBRE2) || '"' || ',';
        v_old := v_old || '"NOMBRE3":' || '"' || TO_CHAR(:OLD.NOMBRE3) || '"' || ',';
        v_new := v_new || '"NOMBRE3":' || '"' || TO_CHAR(:NEW.NOMBRE3) || '"' || ',';
        v_old := v_old || '"APELLIDO1":' || '"' || TO_CHAR(:OLD.APELLIDO1) || '"' || ',';
        v_new := v_new || '"APELLIDO1":' || '"' || TO_CHAR(:NEW.APELLIDO1) || '"' || ',';
        v_old := v_old || '"APELLIDO2":' || '"' || TO_CHAR(:OLD.APELLIDO2) || '"' || ',';
        v_new := v_new || '"APELLIDO2":' || '"' || TO_CHAR(:NEW.APELLIDO2) || '"' || ',';
        v_old := v_old || '"CORREO_ELECTRONICO":' || '"' || TO_CHAR(:OLD.CORREO_ELECTRONICO) || '"' || ',';
        v_new := v_new || '"CORREO_ELECTRONICO":' || '"' || TO_CHAR(:NEW.CORREO_ELECTRONICO) || '"' || ',';
        v_old := v_old || '"POSICION":' || '"' || TO_CHAR(:OLD.POSICION) || '"' || ',';
        v_new := v_new || '"POSICION":' || '"' || TO_CHAR(:NEW.POSICION) || '"' || ',';
        v_old := v_old || '"ID_EQUIPO":' || '"' || TO_CHAR(:OLD.ID_EQUIPO) || '"' || ',';
        v_new := v_new || '"ID_EQUIPO":' || '"' || TO_CHAR(:NEW.ID_EQUIPO) || '"' || ',';
        v_old := v_old || '"ID_UBICACION":' || '"' || TO_CHAR(:OLD.ID_UBICACION) || '"' || ',';
        v_new := v_new || '"ID_UBICACION":' || '"' || TO_CHAR(:NEW.ID_UBICACION) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES ('JUGADOR', 'UPDATE', USER, v_old, v_new);

    ELSIF DELETING THEN
        v_old := v_old || '"ID_JUGADOR":' || '"' || TO_CHAR(:OLD.ID_JUGADOR) || '"' || ',';
        v_old := v_old || '"NOMBRE1":' || '"' || TO_CHAR(:OLD.NOMBRE1) || '"' || ',';
        v_old := v_old || '"NOMBRE2":' || '"' || TO_CHAR(:OLD.NOMBRE2) || '"' || ',';
        v_old := v_old || '"NOMBRE3":' || '"' || TO_CHAR(:OLD.NOMBRE3) || '"' || ',';
        v_old := v_old || '"APELLIDO1":' || '"' || TO_CHAR(:OLD.APELLIDO1) || '"' || ',';
        v_old := v_old || '"APELLIDO2":' || '"' || TO_CHAR(:OLD.APELLIDO2) || '"' || ',';
        v_old := v_old || '"CORREO_ELECTRONICO":' || '"' || TO_CHAR(:OLD.CORREO_ELECTRONICO) || '"' || ',';
        v_old := v_old || '"POSICION":' || '"' || TO_CHAR(:OLD.POSICION) || '"' || ',';
        v_old := v_old || '"ID_EQUIPO":' || '"' || TO_CHAR(:OLD.ID_EQUIPO) || '"' || ',';
        v_old := v_old || '"ID_UBICACION":' || '"' || TO_CHAR(:OLD.ID_UBICACION) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR)
        VALUES ('JUGADOR', 'DELETE', USER, v_old);
    END IF;
END;
/

-- Trigger para la tabla PARTIDO
CREATE OR REPLACE TRIGGER TRG_PARTIDO_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON PARTIDO
FOR EACH ROW
DECLARE
    v_old CLOB := '{';
    v_new CLOB := '{';
BEGIN
    IF INSERTING THEN
        v_new := v_new || '"ID_PARTIDO":' || '"' || TO_CHAR(:NEW.ID_PARTIDO) || '"' || ',';
        v_new := v_new || '"FECHA_HORA_JUEGO":' || '"' || TO_CHAR(:NEW.FECHA_HORA_JUEGO) || '"' || ',';
        v_new := v_new || '"ID_UBICACION":' || '"' || TO_CHAR(:NEW.ID_UBICACION) || '"' || ',';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_NUEVO)
        VALUES ('PARTIDO', 'INSERT', USER, v_new);

    ELSIF UPDATING THEN
        v_old := v_old || '"ID_PARTIDO":' || '"' || TO_CHAR(:OLD.ID_PARTIDO) || '"' || ',';
        v_new := v_new || '"ID_PARTIDO":' || '"' || TO_CHAR(:NEW.ID_PARTIDO) || '"' || ',';
        v_old := v_old || '"FECHA_HORA_JUEGO":' || '"' || TO_CHAR(:OLD.FECHA_HORA_JUEGO) || '"' || ',';
        v_new := v_new || '"FECHA_HORA_JUEGO":' || '"' || TO_CHAR(:NEW.FECHA_HORA_JUEGO) || '"' || ',';
        v_old := v_old || '"ID_UBICACION":' || '"' || TO_CHAR(:OLD.ID_UBICACION) || '"' || ',';
        v_new := v_new || '"ID_UBICACION":' || '"' || TO_CHAR(:NEW.ID_UBICACION) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES ('PARTIDO', 'UPDATE', USER, v_old, v_new);

    ELSIF DELETING THEN
        v_old := v_old || '"ID_PARTIDO":' || '"' || TO_CHAR(:OLD.ID_PARTIDO) || '"' || ',';
        v_old := v_old || '"FECHA_HORA_JUEGO":' || '"' || TO_CHAR(:OLD.FECHA_HORA_JUEGO) || '"' || ',';
        v_old := v_old || '"ID_UBICACION":' || '"' || TO_CHAR(:OLD.ID_UBICACION) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR)
        VALUES ('PARTIDO', 'DELETE', USER, v_old);
    END IF;
END;
/

-- Trigger para la tabla PARTIDO_EQUIPO
CREATE OR REPLACE TRIGGER TRG_PARTIDO_EQUIPO_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON PARTIDO_EQUIPO
FOR EACH ROW
DECLARE
    v_old CLOB := '{';
    v_new CLOB := '{';
BEGIN
    IF INSERTING THEN
        v_new := v_new || '"ID_PARTIDO":' || '"' || TO_CHAR(:NEW.ID_PARTIDO) || '"' || ',';
        v_new := v_new || '"ID_EQUIPO":' || '"' || TO_CHAR(:NEW.ID_EQUIPO) || '"' || ',';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_NUEVO)
        VALUES ('PARTIDO_EQUIPO', 'INSERT', USER, v_new);

    ELSIF UPDATING THEN
        v_old := v_old || '"ID_PARTIDO":' || '"' || TO_CHAR(:OLD.ID_PARTIDO) || '"' || ',';
        v_new := v_new || '"ID_PARTIDO":' || '"' || TO_CHAR(:NEW.ID_PARTIDO) || '"' || ',';
        v_old := v_old || '"ID_EQUIPO":' || '"' || TO_CHAR(:OLD.ID_EQUIPO) || '"' || ',';
        v_new := v_new || '"ID_EQUIPO":' || '"' || TO_CHAR(:NEW.ID_EQUIPO) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES ('PARTIDO_EQUIPO', 'UPDATE', USER, v_old, v_new);

    ELSIF DELETING THEN
        v_old := v_old || '"ID_PARTIDO":' || '"' || TO_CHAR(:OLD.ID_PARTIDO) || '"' || ',';
        v_old := v_old || '"ID_EQUIPO":' || '"' || TO_CHAR(:OLD.ID_EQUIPO) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR)
        VALUES ('PARTIDO_EQUIPO', 'DELETE', USER, v_old);
    END IF;
END;
/

-- Trigger para la tabla GOL
CREATE OR REPLACE TRIGGER TRG_GOL_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON GOL
FOR EACH ROW
DECLARE
    v_old CLOB := '{';
    v_new CLOB := '{';
BEGIN
    IF INSERTING THEN
        v_new := v_new || '"ID_GOL":' || '"' || TO_CHAR(:NEW.ID_GOL) || '"' || ',';
        v_new := v_new || '"MINUTO":' || '"' || TO_CHAR(:NEW.MINUTO) || '"' || ',';
        v_new := v_new || '"DESCRIPCION":' || '"' || TO_CHAR(:NEW.DESCRIPCION) || '"' || ',';
        v_new := v_new || '"ID_JUGADOR":' || '"' || TO_CHAR(:NEW.ID_JUGADOR) || '"' || ',';
        v_new := v_new || '"ID_PARTIDO":' || '"' || TO_CHAR(:NEW.ID_PARTIDO) || '"' || ',';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_NUEVO)
        VALUES ('GOL', 'INSERT', USER, v_new);

    ELSIF UPDATING THEN
        v_old := v_old || '"ID_GOL":' || '"' || TO_CHAR(:OLD.ID_GOL) || '"' || ',';
        v_new := v_new || '"ID_GOL":' || '"' || TO_CHAR(:NEW.ID_GOL) || '"' || ',';
        v_old := v_old || '"MINUTO":' || '"' || TO_CHAR(:OLD.MINUTO) || '"' || ',';
        v_new := v_new || '"MINUTO":' || '"' || TO_CHAR(:NEW.MINUTO) || '"' || ',';
        v_old := v_old || '"DESCRIPCION":' || '"' || TO_CHAR(:OLD.DESCRIPCION) || '"' || ',';
        v_new := v_new || '"DESCRIPCION":' || '"' || TO_CHAR(:NEW.DESCRIPCION) || '"' || ',';
        v_old := v_old || '"ID_JUGADOR":' || '"' || TO_CHAR(:OLD.ID_JUGADOR) || '"' || ',';
        v_new := v_new || '"ID_JUGADOR":' || '"' || TO_CHAR(:NEW.ID_JUGADOR) || '"' || ',';
        v_old := v_old || '"ID_PARTIDO":' || '"' || TO_CHAR(:OLD.ID_PARTIDO) || '"' || ',';
        v_new := v_new || '"ID_PARTIDO":' || '"' || TO_CHAR(:NEW.ID_PARTIDO) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        v_new := RTRIM(v_new, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES ('GOL', 'UPDATE', USER, v_old, v_new);

    ELSIF DELETING THEN
        v_old := v_old || '"ID_GOL":' || '"' || TO_CHAR(:OLD.ID_GOL) || '"' || ',';
        v_old := v_old || '"MINUTO":' || '"' || TO_CHAR(:OLD.MINUTO) || '"' || ',';
        v_old := v_old || '"DESCRIPCION":' || '"' || TO_CHAR(:OLD.DESCRIPCION) || '"' || ',';
        v_old := v_old || '"ID_JUGADOR":' || '"' || TO_CHAR(:OLD.ID_JUGADOR) || '"' || ',';
        v_old := v_old || '"ID_PARTIDO":' || '"' || TO_CHAR(:OLD.ID_PARTIDO) || '"' || ',';
        v_old := RTRIM(v_old, ',') || '}';
        INSERT INTO BITACORA_CAMBIOS (NOMBRE_TABLA, OPERACION, USUARIO_BD, VALOR_ANTERIOR)
        VALUES ('GOL', 'DELETE', USER, v_old);
    END IF;
END;
commit;
/

